exclude non-release tags, improve portability of bash builtin & sed usage

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,8 +2,8 @@
 
 set -e
 
-[ -n "$ASDF_INSTALL_VERSION" ] || (echo $'Missing ASDF_INSTALL_VERSION' 1>&2 && exit 1)
-[ -n "$ASDF_DOWNLOAD_PATH" ] || (echo $'Missing ASDF_DOWNLOAD_PATH' 1>&2 && exit 1)
+[ -n "$ASDF_INSTALL_VERSION" ] || (echo "Missing ASDF_INSTALL_VERSION" 1>&2 && exit 1)
+[ -n "$ASDF_DOWNLOAD_PATH" ] || (echo "Missing ASDF_DOWNLOAD_PATH" 1>&2 && exit 1)
 
 case "$(uname -s)" in
   "Darwin")
@@ -13,7 +13,7 @@ case "$(uname -s)" in
     RELEASE_FILENAME="mongosh-$ASDF_INSTALL_VERSION-linux.tgz"
     ;;
   *)
-    echo $'Unknown operating system' 1>&2 && exit 1
+    echo "Unknown operating system" 1>&2 && exit 1
     ;;
 esac
 
@@ -22,6 +22,6 @@ esac
     tar xzf - -C "$ASDF_DOWNLOAD_PATH" &&
     exit 0
 ) || (
-  echo $'Download failed' 1>&2 &&
+  echo "Download failed" 1>&2 &&
     exit 1
 )
