fix upstream packaging breaking the plugin for mongosh versions >= 0.15.1, rewrite scripts, add dependabot

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,22 +1,39 @@
-#!/bin/bash
-
-set -e
+#!/usr/bin/env bash
 
 : "${ASDF_INSTALL_PATH:?"Missing ASDF_INSTALL_PATH"}"
-: "${ASDF_INSTALL_TYPE:?"asdf-mongosh supports release installs only"}"
-
 : "${ASDF_DOWNLOAD_PATH:?"Missing ASDF_DOWNLOAD_PATH"}"
+: "${ASDF_INSTALL_TYPE:?"asdf-mongosh supports release installs only"}"
+: "${ASDF_INSTALL_VERSION:?"Missing ASDF_INSTALL_VERSION"}"
 
-# shellcheck source=SCRIPTDIR/download
-[ -f "$ASDF_DOWNLOAD_PATH" ] || . "$(dirname "$0")/download" || (echo "Download failed." >&2 && exit 1)
+# shellcheck source=SCRIPTDIR/lib
+source "$(dirname "$0")/lib"
 
-(
+install() {
+  if [ ! -d "$ASDF_DOWNLOAD_PATH" ]; then
+    # shellcheck source=SCRIPTDIR/download
+    source "$(dirname "$0")/download" || (echo "Downloading mongosh $ASDF_INSTALL_VERSION failed" 1>&2; exit1)
+  fi
+
+  # Workaround for change in mongosh release packaging, see:
+  # https://github.com/mongodb-js/mongosh/pull/955
+  if [ ! -d "$ASDF_DOWNLOAD_PATH/bin" ]; then
+    mv "$ASDF_DOWNLOAD_PATH/mongosh-$(get_release_version)-$(get_release_os)-$(get_release_arch)/bin" "$ASDF_DOWNLOAD_PATH"
+    find "$ASDF_DOWNLOAD_PATH/mongosh-$(get_release_version)-$(get_release_os)-$(get_release_arch)" -delete
+  fi
+
   mv "$ASDF_DOWNLOAD_PATH/bin" "$ASDF_INSTALL_PATH" &&
+    find "$ASDF_INSTALL_PATH" &&
     chmod -R +x "$ASDF_INSTALL_PATH/bin" &&
-    echo "mongosh has been installed." &&
-    rm -rf "$ASDF_DOWNLOAD_PATH"
-) || (
-  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH" &&
-    echo "An error ocurred while installing mongosh $ASDF_INSTALL_VERSION" 1>&2 &&
+    find "$ASDF_DOWNLOAD_PATH" -delete
+
+  if [ -x "$ASDF_INSTALL_PATH/bin/mongosh" ]; then
+    echo "mongosh $ASDF_INSTALL_VERSION has been installed"
+    exit 0
+  else
+    echo "An error ocurred while installing mongosh $ASDF_INSTALL_VERSION" 1>&2
+    find "$ASDF_INSTALL_PATH" -delete
     exit 1
-)
+  fi
+}
+
+install
